### ISSUE TITLE
[V3] - Very complicated to add new storage

### ISSUE THREAD

**Issue by thibaut-algrin** [novaway/NovawayFeatureFlagBundle#50]
Hello,

It is very complicated to add new storage. Indeed, I would like to add a Doctrine ORM Storage but actually we can't inject EntityManagerInterface in storage's construct.

I think we need to remove factory for storages except ArrayStorage.

**Comment by jdecool** [comment]
Hi,

You're completely right.

V3 is under development.

I've created a demo project I'm using to validate the new bundle version usage.
In it I've created 3 different storage to ensure the bundle design.

It will involve soon.

Thanks for your feedback.

**Comment by thibaut-algrin** [comment]
Do you need help? How can I help you?
